FROM python:3.8-slim-buster

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN pip3 install pytest==7.1.1

COPY . /app

ENTRYPOINT ["python3", "-m", "pytest"]